config/routes.rb
Rails.application.routes.draw do
  resources :contacts, :only => [:create]
  get '/', as: 'welcome_index', to: 'welcome#index'
  get '/what-is-an-mvp', as: 'what_is_mvp', to: 'pages#what_is_an_mvp'
  get '/where-to-begin-when-building-an-application', as: 'building_an_application', to: 'pages#building_an_application_where_to_begin'
  get '/build-ecommerce-app', as: 'build_ecommerce_app', to: 'pages#build_ecommerce_app'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { render :show, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
        ContactMailer.with(contact: @contact).contact_email.deliver_later
      else
        format.html { render welcome_index_path }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def what_is_an_mvp
    set_meta_tags(
      title: 'What is an MVP',
      description: 'Learn what an MVP is and start validating your ideas without spending too many resources',
      keywords: 'mvp, blackmountain, what is an mvp',
      index: true,
      follow: true,
      og: {
        locale: 'en_US',
        type: 'website',
        title: 'What is an MVP - BlackMountain',
        description: 'Learn what an MVP is and start validating your ideas without spending too many resources.',
        url: 'https://black-mountain.com.ar/what-is-an-mvp',
        site_name: 'BlackMountain'
      },
      twitter: {
        card: 'summary_large_image',
        image: view_context.asset_pack_path('media/images/header-background-3.jpg'),
        creator: '@BlackMountainAR',
        site: '@BlackMountainAR'
      }
    )
  end

  def building_an_application_where_to_begin
    set_meta_tags(
      title: 'Where to begin when building an application',
      description: 'Learn a few tips on how to begin the process of building a new application.',
      keywords: 'mvp, blackmountain, build application, starting new application',
      index: true,
      follow: true,
      og: {
        locale: 'en_US',
        type: 'website',
        title: 'Where to begin when building an application - BlackMountain',
        description: 'Learn a few tips on how to begin the process of building a new application.',
        url: 'https://black-mountain.com.ar/where-to-begin-when-building-an-application',
        site_name: 'BlackMountain'
      },
      twitter: {
        card: 'summary_large_image',
        image: view_context.asset_pack_path('media/images/header-background-3.jpg'),
        creator: '@BlackMountainAR',
        site: '@BlackMountainAR'
      }
    )
  end

  def build_ecommerce_app
    set_meta_tags(
      title: 'Build your ecommerce application',
      description: 'We build your ecommerce application in one month.',
      keywords: 'ecommerce app builder, companies that build apps, app making company',
      index: true,
      follow: true,
      og: {
        locale: 'en_US',
        type: 'website',
        title: 'Build your ecommerce application - BlackMountain',
        description: 'We build your ecommerce application in one month.',
        url: 'https://black-mountain.com.ar/build-ecommerce-app',
        site_name: 'BlackMountain'
      },
      twitter: {
        card: 'summary_large_image',
        image: view_context.asset_pack_path('media/images/header-background-3.jpg'),
        creator: '@BlackMountainAR',
        site: '@BlackMountainAR'
      }
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contact = Contact.new
    set_meta_tags(
      title: 'We build applications',
      description: 'Experts in app development and design. Freelance team. We make your ideas a reality.',
      keywords: 'mvp, blackmountain, developers, react, quality assurance, automation, application, build web application, build application, javascript, app developers',
      index: true,
      follow: true,
      og: {
        locale: 'en_US',
        type: 'website',
        title: 'We build applications - BlackMountain',
        description: 'Experts in app development and design. Freelance team. We make your ideas a reality.',
        url: 'https://black-mountain.com.ar',
        site_name: 'BlackMountain'
      },
      twitter: {
        card: 'summary_large_image',
        image: view_context.asset_pack_path('media/images/header-background-3.jpg'),
        creator: '@BlackMountainAR',
        site: '@BlackMountainAR'
      }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <div class="form-group text-left">
    <%= form.label :name, class: "ml-3" %>
    <%= form.text_field :name, class: "shadow-sm form-control rounded control-lg form-control-lg border-0 p-4" %>
  </div>

  <div class="form-group text-left">
    <%= form.label :email, class: "ml-3" %>
    <%= form.email_field :email, class: "shadow-sm form-control rounded control-lg form-control-lg border-0 p-4" %>
  </div>

  <div class="form-group text-center">
    <%= form.submit "Contact", class: buttonCss %>
  </div>
<% end %>

app/views/contacts/_form_ecommerce.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <%= form.hidden_field :description, value: "ecommerce" %>

  <div class="form-group text-left">
    <%= form.label :name, class: "ml-3" %>
    <%= form.text_field :name, class: "border shadow-sm form-control rounded control-lg form-control-lg p-4" %>
  </div>

  <div class="form-group text-left">
    <%= form.label :email, class: "ml-3" %>
    <%= form.email_field :email, class: "border shadow-sm form-control rounded control-lg form-control-lg p-4" %>
  </div>

  <div class="form-group text-center">
    <%= form.submit "Contact", class: "btn btn-lg btn-orange px-4 rounded-pill" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<section class="section header d-flex">
    <div class="container align-self-center">
        <div class="row py-4 m-4">
            <div class="col text-center">
                <h1 class="text-dark">
                  Thank you for contacting us.<br />
                  We will get back to you as soon as possible.
                </h1>
                <a class="zoom-animation header-how-button shadow btn btn-primary btn-big rounded-pill mt-3 px-5 py-2" href="/">
                    Go back
                </a>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-153279158-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-153279158-1');
        </script>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="google-site-verification" content="XKPpMZl7-1muamPsg3HHWQGo_C4eOrO6LRy1rfXcyQA" />
        <meta name="detectify-verification" content="3de98ebd1672a395f8b2a850f508c3ac" />

        <!-- Google fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;400;800&family=Maven+Pro&family=Montserrat:wght@800&display=swap" rel="stylesheet">

        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">
        <%= display_meta_tags site: 'BlackMountain' %>
        <%= stylesheet_pack_tag 'application' %>
    </head>
    <body data-spy="scroll" data-target="#navbar" data-offset="100">
        <nav id="navbar" class="navbar">
            <div class="container">
                <a class="navbar-brand mx-auto" href="/">
                    <%= image_pack_tag "logo-alt.png", height: "18" %>
                </a>
                <div class="d-none mx-auto d-sm-block font-weight-bold">
                    <ul class="nav justify-content-end align-items-center">
                        <li class="nav-item">
                            <%= link_to "Who are we", welcome_index_path(anchor: "who-are-we", utm_source: "website", utm_medium: "navbar", utm_campaign: "interaction"), class: "nav-link btn-nav-outline" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "How do we work", welcome_index_path(anchor: "how-do-we-work", utm_source: "website", utm_medium: "navbar", utm_campaign: "interaction"), class: "nav-link btn-nav-outline" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Why us", welcome_index_path(anchor: "why-us", utm_source: "website", utm_medium: "navbar", utm_campaign: "interaction"), class: "nav-link btn-nav-outline" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Get in touch", welcome_index_path(anchor: "get-in-touch", utm_source: "website", utm_medium: "navbar", utm_campaign: "interaction"), class: "nav-link btn-nav-outline" %>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= yield %>
        <section class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 col-md-6 text-center mb-4">
                        <%= image_pack_tag "logo-alt.png", style: "width: 256px; margin-top: -25px" %>
                    </div>
                    <div class="col-12 col-md-3">
                        <h6 class="font-weight-bold">COMPANY</h6>
                        <ul class="list-unstyled">
                            <li class="py-2">
                                <%= link_to "Our services", welcome_index_path(anchor: "what-do-we-do", utm_source: "website", utm_medium: "footer", utm_campaign: "interaction") %>
                            </li>
                            <li class="py-2">
                                <%= link_to "Build e-commerce application", build_ecommerce_app_path(utm_source: "website", utm_medium: "footer", utm_campaign: "ecommerce") %>
                            </li>
                            <li class="py-2">
                                <%= link_to "Why working with us?", welcome_index_path(anchor: "why-us", utm_source: "website", utm_medium: "footer", utm_campaign: "interaction") %>
                            </li>
                            <li class="py-2">
                                <%= link_to "How do we work?", welcome_index_path(anchor: "how", utm_source: "website", utm_medium: "footer", utm_campaign: "interaction") %>
                            </li>
                            <li class="py-2">
                                <%= link_to "Get in touch", welcome_index_path(anchor: "get-in-touch", utm_source: "website", utm_medium: "footer", utm_campaign: "interaction") %>
                            </li>
                        </ul>
                    </div>
                    <div class="col-12 col-md-3">
                        <h6 class="font-weight-bold">SOCIAL MEDIA</h6>
                        <ul class="list-unstyled">
                            <li class="py-2">
                                <a href="https://www.linkedin.com/company/blackmountain-solutions">LinkedIn</a>
                            </li>
                            <li class="py-2">
                                <a href="https://github.com/BlackMountainSolutions">GitHub</a>
                            </li>
                            <li class="py-2">
                                <a href="https://twitter.com/BlackMountainAR">Twitter</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </body>
</html>

app/views/pages/building_an_application_where_to_begin.html.erb
<div class="pages">
    <div class="header">
        <div class="container">
            <h1>Building an application, where to begin?</h1>
            <h3>Start on the right foot</h3>
        </div>
    </div>
    <div class="container content border">
        <div class="author">
            <%= image_pack_tag 'franco-montenegro.jpg', class: "avatar mr-3" %>
            <div class="mt-2">
                <h5 class="m-0">By Franco Montenegro</h5>
                <p class="lead m-0">Founder of BlackMountain</p>
            </div>
        </div>

        <p class="lead">
            It is always exciting to begin a new project. You have a great idea on your mind; you are already thinking about features, tiers, styles, and what have you, but <b>how can you be sure it will work and people will find it interesting?</b>
        </p>

        <%= image_pack_tag 'pages/thinking-your-next-application.jpg', class: 'd-block my-4 mx-auto img-fluid shadow border' %>
        <span class="d-block text-center text-muted">Photo by <a href="https://unsplash.com/@austindistel?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Austin Distel</a> on <a href="https://unsplash.com/s/photos/web-application?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>

        <h2 class="title">It begins with a problem</h2>
        <p class="lead">
            <b>Successful applications are those who solve people's problems, real problems</b>. And the best type of problem you may want to address is one you currently are experiencing. You know the inner details of these issues you are experiencing, you know what the real hassle is, and you know it is a real problem. The next step is to validate how many people are having this problem and what your competition will be.
        </p>

        <h2 class="title">Is the problem you are trying to solve experienced by many?</h2>
        <p class="lead">
            It is good to be solving problems, but you want to <b>make sure you are solving problems experienced by a large number of people</b>. Otherwise, you will end up with an application only used for only a few. Next step is to do a quick research, <b>how popular is the problem?</b> Are people searching for solutions? How is your competition? Is there any competition? Having no competition may be a good or a bad sign, it depends. If you have no competition, it may be because you are the first to tackle the problem, or maybe because the problem is not worth solving it.
        </p>

        <%= image_pack_tag 'pages/research-your-idea.jpg', class: 'd-block my-4 mx-auto img-fluid shadow border' %>
        <span class="d-block text-center text-muted">Photo by <a href="https://unsplash.com/@domenicoloia?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Domenico Loia</a> on <a href="https://unsplash.com/s/photos/web-application?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>

        <h2 class="title">What about your competition?</h2>
        <p class="lead">
            Knowing your competition is critical. You need to know against who you will be competing against, and you have to know your competitor's strengths and weaknesses. <b>You have to be clear about what makes you different and why people should pick your solution</b>. But everything in good measure, know your competition and know them well, but don't get yourself too influenced by them or else, you will end up building a clone of their product or even worse, you will end up with tunnel vision (and thus, unable to innovate and come up with better solutions).
        </p>

        <h2 class="title">Defining your customers</h2>
        <p class="lead">
            Defining your customers and who will be using your platform will make things so much easier and help you stay focused. Delivering a clear solution to a well-defined group of people will allow you to provide a superior solution than if you were trying to solve everybody's problem. <b>Don't be afraid of reducing your audience's scope</b>. Instead of targeting the entire United States, why don't you start with just New York city? With time, you will be able to expand your target, but start small and well at the beginning.
        </p>

        <h2 class="title">Validate your idea</h2>
        <p class="lead">
            Now that you know you may be on to something, it's time to validate your idea. <b>Validating your idea doesn't mean you need to jump and build the most beautiful application you can think of</b>, far from it. Be creative. Try to come up with a cleaver way to let you know if your customers want to use it spending the least amount of resources. An excellent approach for validating your idea is to <%= link_to "build an MPV", what_is_mvp_path %>. The critical point here is not to spend too many resources, Remember, you will be confirming a hypothesis, an idea that may be useful for people.
        </p>

        <h2 class="title">Conclusion</h2>
        <p class="lead">
            It is always better to start small, little by little, and polishing along the way. <b>Make sure you know the problem you are trying to solve</b>, see if this is a widespread problem experienced by many. <b>Don't forget about your competition</b>, but also, don't get too attached to them, you don't want to end up with a clone (nobody likes those!) and make sure you <b>define your audience</b>. Keep these small tips in mind, and you will have a higher chance of ending up with a successful application.
        </p>

        <p class="lead">
            One final word of advice, <b>don't be discouraged if your idea doesn't work</b>. Building an application is a skill, and like any skill, it takes time and practice to get it right. So make sure you enjoy the journey of learning how to build an application!
        </p>

        <h3 class="py-4 my-4 text-center">So tell me, what application is on your mind?</h3>
    </div>
</div>

app/views/pages/what_is_an_mvp.html.erb
<div class="pages">
    <div class="header">
        <div class="container">
            <h1>What is an MVP?</h1>
            <h3>And why you should build one</h3>
        </div>
    </div>
    <div class="container content border">
        <div class="author">
            <%= image_pack_tag 'franco-montenegro.jpg', class: "avatar mr-3" %>
            <div class="mt-2">
                <h5 class="m-0">By Franco Montenegro</h5>
                <p class="lead m-0">Founder of BlackMountain</p>
            </div>
        </div>

        <p class="lead">
            You are about to build your first application; you have this great idea on your mind and can't wait to make it a reality. <b>How can you build this application without going bankrupt?</b>
        </p>

        <%= image_pack_tag 'pages/building-an-mvp.jpg', class: 'd-block my-4 mx-auto img-fluid shadow border' %>

        <h2 class="title">Introducing MVP</h2>
        <p class="lead">
            MVP stands for <a href="https://en.wikipedia.org/wiki/Minimum_viable_product" target="_blank">Minimum Viable Product</a>, and it focuses on <b>building just the minimal to test an idea</b>, to check if a product is attractive to the public or not by using the least amount of resources (money and time).
        </p>

        <h2 class="title">How much time should I spend building my MVP?</h2>
        <p class="lead">
            It's hard to say, especially since every application is a world on itself, but you want to <b>keep it to the very minimum, somewhat between the range from one to three months—no more than that</b>. Remember, we will be building an MVP to gather feedback about our idea, we don't want to spend too many resources here.
        </p>

        <h2 class="title">How do you build an MVP in such short amount of time?</h2>
        <p class="lead">
            So, the whole idea of building something quick to test it out with customers sounds good, but how can you create something usable in such a short amount of time? By removing the exceed of features, or better said, by removing what is not essential to test your idea.
        </p>
        <p class="lead">
            To differentiate between essential features and non-essential ones, ask yourself if I remove this feature, can I still test the main idea? If you can't answer NO, I NEED IT! Without a doubt, it's probably a feature you can remove. Beware of features that sound "cool", those always feature you can remove. When adding a new feature, always ask this question, is it essential? If in doubt, remove it.
        </p>

        <%= image_pack_tag 'pages/mvp.jpg', class: 'd-block my-4 mx-auto img-fluid shadow border' %>

        <h2 class="title">I'm worried my customers will think bad of my application</h2>
        <p class="lead">
            Bad reputation for your application is a valid concern, what if your customers feel wrong about your application? What if it hurts your reputation or brand? There is a big difference between shipping bad software and shipping MVPs. Harmful software may look pretty, may look ugly, it doesn't matter, the main point is, it doesn't work or solve any problem. MVPs are the raw idea, it does only one thing, but it does it well, and that's the key difference, <b>your MVP solves a problem</b>. You are testing to see if your clients have this problem and if your way of solving it is right.
        </p>

        <h2 class="title">Conclusion</h2>
        <p class="lead">
            When building your application, <b>test each step you take using the least amount of resources</b>. Focus on small steps, one at a time, make sure to complete small goals, don't try to tackle the whole world in one go, it won't end well, and you will waste a lot of time and money. Go small and go well.
        </p>

        <h3 class="py-4 my-4 text-center">So, are you ready to build your application?</h3>
    </div>
</div>

app/views/welcome/_already_working_with_us.html.erb
<section class="section already-working-with-us">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-5">
                <h1><strong class="title">Already working with us?</strong></h1>
                <p class="lead">
                    That's great! We provide our clients with a personalized <a href="https://dashboard.black-mountain.com.ar/" target="_blank" rel="nofollow">dashboard</a> where it's easy to know who is on your team, keep track of invoices and... wait for it... because new features are coming.
                </p>
                <p class="lead">Remember to stay tuned since new tools are coming and we plan to open them to the public!</p>
            </div>
        </div>
    </div>
</section>

app/views/welcome/_contact_us.html.erb
<section class="section contact-us" id="get-in-touch">
    <div class="abstract-background"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="text-center mb-5">
                    <h2 class="title">Ready to <span class="font-weight-bold">build your application</span>?</h2>
                    <div class="py-4 w-50 mx-auto">
                        <%= render 'contacts/form', contact: @contact, buttonCss: "btn btn-block btn-orange zoom-animation font-weight-bold btn-lg mt-4 px-4 shadow-sm" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/welcome/_header.html.erb
<section class="section header">
    <div class="header-content container-fluid align-self-center text-center">
        <h1>Web application development</h1>
        <h4>
            Our mission is to build high quality web applications. Ready to build your idea?
        </h4>
        <%= link_to "Build e-commerce application", build_ecommerce_app_path, class: "mb-4 zoom-animation btn btn-orange btn-lg rounded-0 mx-2" %>
        <%= link_to "Build custom application", "#get-in-touch", class: "mb-4 zoom-animation btn btn-white btn-lg rounded-0 mx-2" %>
        <p class="text-white lead mb-2"><b>Don't know where to begin?</b> Maybe <%= link_to "some of our suggestions", building_an_application_path, class: "btn-link" %> can help you.</p>
        <p class="text-white lead mb-2"><b>Already have an idea in mind?</b> Learn <%= link_to "how to validate it", what_is_mvp_path, class: "btn-link" %>.</p>
    </div>
</section>

app/views/welcome/_need_help.html.erb
<section class="section need-help">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-5">
                <h2 class="title">Need help?</h2>
                <p class="lead">
                    If you are just starting or maybe don't know where to begin, don't worry we got your back!
                </p>

                <%= link_to building_an_application_path, class: "article-link" do %>
                    <h3 class="m-0">Building an application, where to begin?</h3>
                    <p class="m-0 lead">We share with you some of the tips to keep in mind when starting a new application.</p>
                <% end %>
                <%= link_to what_is_mvp_path, class: "article-link" do %>
                    <h3 class="m-0">Efficient way of validating an idea</h3>
                    <p class="m-0 lead">Learn how to validate your next project without spending too many resources.</p>
                <% end %>
            </div>
        </div>
        <h3 class="text-center mt-4">Still need help?<br />Drop us a line, we would love to chat with you</h3>
    </div>
</section>

app/views/welcome/_what_do_we_do.html.erb
<section class="section what-do-we-do" id="how-do-we-work">
    <div class="container">
        <div class="mb-4">
            <h2 class="title">How do we work?<h2>
            <h3>We ensure high-quality results in time by following these simple steps:</h3>
        </div>
        <div class="row">
            <div class="col-lg-6 mb-4">
                <div class="card">
                    <h4>#1 Define the objetive</h4>
                    <p class="lead">
                        We first want to know what we are building and what problems we are solving. Remember, a successful application is one that solves people's problems, REAL problems.
                    </p>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card">
                    <h4>#2 Define scopes</h4>
                    <p class="lead">
                        We set real and achievable goals. We always try to work on small chunks of work to be able to get feedback. Short and well-defined goals will ensure we are on the right track!
                    </p>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card">
                    <h4>#3 Designs</h4>
                    <p class="lead">
                        After we know what we need to do, we work on designs, layouts, and general styling. How are we going to present the content? Which colors will we use?
                    </p>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card">
                    <h4>#4 Implement</h4>
                    <p class="lead">
                        We start coding and making what we plan a reality. Relying on trusted technology such as ReactJS, AWS, ReactNative, and much more gives us high-quality results on time.
                    </p>
                </div>
            </div>
        </div>
        <h3 class="text-center mt-4">Is that simple, <span class="font-weight-bold">we do not overcomplicate things</span>.</h3>
    </div>
</section>